neotree.el

Hi Pei,
This PR adds a new defcustom `neo-show-hidden-files` to show the hidden files by default.
Cheers,
syl20bnr

Add neo-show-hidden-files defcustom

---

neotree.el

Hi Pei,
This PR removes the newline if one set both `neo-banner-message` and `neo-show-updir-line` to `nil`.
(left: before / right: after)
Cheers,
syl20bnr

Remove newline when neo-banner-message neo-show-updir-line are nil

---

neotree.el

Hi Pei,
This PR makes the `neotree` mode-line format fits in the current window size.
Cheers,
syl20bnr

Truncate the directory to fit window size in the mode-line

---

neotree.el

Hi Pei,
This PR add prefix arguments to `neotree-enter` to open a node in a split window:
- <kbd>|</kbd> (pipe) for a vertical split
- <kbd>-</kbd> for an horizontal split
Cheers,
syl20bnr

Open a node in a vertically or horizontally split window

---

neotree.el

Hi Pei,
I'm sure that this additional indentation has been added on purpose but it breaks readability.
See the screenshots below, the first one shows the files has if they were in the extensions directory which is wrong.
Now I think this additional indentation has been added because when there are only files in a directory they appear on the same indent level as the parent directory, but this is OK and consistent with the display of the root and its content.
Before (left) / After (right):
Cheers,
syl20bnr

Fix bad indentation of files

---

neotree.el

* Replaces empty `neotree-options` group with the `neotree` group
* Puts the group under the correct category of Files
* Removes the empty info link

Correct customisation group

---

neotree.el

This adds a neo-modern-sidebar customizable variable, which always forces Neotree into a full frame-height left-most window.  It's meant to mimic sidebar functionality in modern GUI editors.

Modern sidebar-like functionality

---

neotree.el

'emacs -Q -l neotree.el' is failed with original code because
(locate-library "neotree") returns nil in such case.

Improve setting neo-dir

---

neotree.el

Original code raises error if new name file is already existed.
This is related to #145.

Confirm overwrite at renaming

---

neotree.el

otherwise the cycle stops when the error is thrown and the whole file list is not populated

fix `vc-responsible-backend` throwing when a leaf node was not tracked by a VCS

---

neotree.el

As proposed in #173, this allows the user to customize where neotree is displayed, but keeps the original behavior as the default behavior.

Use customizable display action to show neotree

---

neotree.el

'neotree-quick-look' is added to provide Quick Look like open event. When user type 'SPC' in a neotree buffer, the selected file will be rendered in other window, but the cursor will be kept in the same position in the neotree buffer. So user can quickly check the content of each file.

Add Quick Look like NeoTree open event

---

neotree.el

When you go to a new file which is not in the current neotree root and run `neotree-find`; it will prompt you if you want to change root. This option will allow you to skip the prompt and always answer yes.

Allow changing root without prompt

---

neotree.el

This adds a command `a` that lets the user pick the target window using [ace-window](https://github.com/abo-abo/ace-window).
By the way, I realized your dev branch is 85 commits ahead of master. I believe the MELPA package is built from the master branch. Is that incorrect or don't you think it's time to update master?

Add ace-window integration

---

neotree.el

Hi there, I'm not sure if you're interested in this, but I've been working on a library called [`all-the-icons`](https://github.com/domtronn/all-the-icons.el) recently which helps with the use of Font Icons within Emacs - I felt that NeoTree was the perfect candidate to show it off, and so I've added a theme to NeoTree which displays the File Type icon / Folder icon next to file and directory entries.
The downside is that this depends on lots of font families being used at once, which means it won't work in a terminal or non window system. But for GUI based Emacs', I think it's a really nice addition to the package, and users can account for both using like;
```elisp
(setq neo-theme (if window-system 'arrow 'icons))
```
Here's a screenshot to show you how NeoTree can look with the use of …

Add `all-the-icons` Integration

---

neotree.el

`display-buffer-in-side-window` prevent the awkward situation that neotree becomes the only window in the emacs and no split can work. Besides,  previous attempts using `defadvice` on `delete-window` and `delete-other-window` is hard to reason.
You can test this by using 'C-x 0' on the main window by using the following startup script to check if the awkward moment comes.
```
(setq debug-on-error t
el-get-verbose t)
(setq inhibit-startup-screen nil)
(add-to-list 'load-path ".")
(require 'neotree)
(neotree-toggle)
```

create the neotree window by `display-buffer-in-side-window`.

---

neotree.el

This is an unused and unnecessary variable since 8ae43c1.

Remove neo-persist-show

---

neotree.el

This helps when you start emacs with `--daemon` and use GUI and tty
simultaneously. Fix #194
* Use `display-graphic-p` instead of `window-system` which is deprecated for
predicate use
The only caveat is if you open neotree in GUI and switch to same window in
terminal you won't get icons. Workaround is to toggle `neotree` in tty to switch
back to `+-` default theme.

Use graphic themes only when it's available/usable

---

neotree.el

winum is the new, extended and maintained version of window-numbering
https://github.com/deb0ch/emacs-winum

add support for winum window numbers

---

neotree.el

Unlike the screen-shot on the front-page, ascii theme was missing spaces between the character and the directory.

Ascii theme had odd spacing

---

neotree.el

This makes it possible to jump several lines at a time by typing a digit-argument before navigating up or down.

update next/prev line, optional count argument

---

neotree.el

Hi, this PR customizes the messages neotree displays when the mouse moves onto the nodes.

Customize help-echo messages for neotree nodes

---

neotree.el

Currently ```neotree-create-node``` function create only one directory, this change adds possibility to create subdirectories and parent directories in the same call.
ie.
`newdir/subdir1/subdir2/subdir3/`

fix create recursive directories

---

neotree.el

I'm trying to use NeoTree with TRAMP (via Spacemacs) but found that a call to `(neotree-find (projectile-project-root))` from within TRAMP is causing Emacs to hang.
After some debugging, it looks like the loop inside `neo-buffer--select-file-node` from within TRAMP environment would never return, as `iter-curr-dir` will never be `/` since NeoTree is dealing with remote file, the root path will looks like `/ssh:10.0.1.2:/`. 
In this PR, I called `file-remote-p` to return local name for remote path, which fixed the issue.

Improve compatibility with remote files

---

neotree.el

Fixes #149 
This makes it so when smart-open is enabled AND you are in a projectile project, the root is set to projectile-root. Otherwise behavior should be the same as before.

Adding in projectile support for smart-open

---

neotree.el

Added the keybinding C-c C-a for collapsing all expanded folders in the
neotree buffer
modified:   neotree.el

Added neotree-collapse-all as a fix to issue#227

---

neotree.el

Right now, the `dir-fn` sets the `default-directory` without the trailing `/`, which confuses functions like `counsel-find-file`.
This issue is referenced here(other project): https://github.com/syl20bnr/spacemacs/issues/9199

Fix the neo-buffer--post-move default-directory

---

neotree.el

Hi!
I send change function name [PR](https://github.com/domtronn/all-the-icons.el/pull/181) to all-the-icons.
This breaks this package, so I send this PR.

Fix all-the-icons-icon-for-dir to ~icon-for-dir-with-chevron
